### PR TITLE
Fix some installation issues on MacOS

### LINKED ISSUE #109: MethodError: no method matching `joinpath(::typeof(Libdl.dlpath), ::String))`
Xpress.jl doesn't work on MacOS with version `v0.12.1`. `v0.11.1` works fine though.

```plaintext
$ git checkout v0.11.1
Previous HEAD position was 1e563eb Update Project.toml
HEAD is now at bf17091 Update Project.toml (#97)

$ julia --project -e "using Xpress;"
[ Info: Xpress: Development license detected.

$ git log -n1
commit bf170918bdb949103c5b6161349006b77e2a52e6 (HEAD, tag: v0.11.1)
Date:   Mon Sep 21 09:03:40 2020 +1200

    Update Project.toml (#97)

$ git checkout -- . && git checkout v0.12.1
Previous HEAD position was bf17091 Update Project.toml (#97)
HEAD is now at 1e563eb Update Project.toml

$ julia --project -e "using Xpress;"
WARNING: redefinition of constant libxprs. This may fail, cause incorrect answers, or produce other errors.
ERROR: InitError: MethodError: no method matching joinpath(::typeof(Libdl.dlpath), ::String)
Closest candidates are:
  joinpath(::AbstractString, ::AbstractString...) at path.jl:289
Stacktrace:
 [1] initialize() at /Users/USER/gitrepos/Xpress.jl/src/Xpress.jl:46
 [2] __init__() at /Users/USER/gitrepos/Xpress.jl/src/Xpress.jl:61
 [3] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
 [4] _require_from_serialized(::String) at ./loading.jl:749
 [5] _require(::Base.PkgId) at ./loading.jl:1040
 [6] require(::Base.PkgId) at ./loading.jl:928
 [7] require(::Module, ::Symbol) at ./loading.jl:923
during initialization of module Xpress

$ git log -n1
commit 1e563eb81895817a449a866d5622e10fa70ab0fc (HEAD, tag: v0.12.1, origin/master, origin/HEAD, master)
Date:   Fri Oct 30 11:33:42 2020 -0300

    Update Project.toml

```

### PR DESCRIPTION
**Pull request by kdheepak**
1) `dlpath` is a function that exists in `Libdl`.

Screen Shot 2020-11-19 at 4 13 06 PM

I've changed the name from `dlpath` to `xpressdlpath`. Other variable name suggestions welcome.

2) I think we should use the explicit path to `libxprs`. On MacOS, even though this function is called on initialize:

https://github.com/jump-dev/Xpress.jl/blob/master/src/Xpress.jl#L46

when the first call into the library is made, Julia is not able to locate the library.

```
$ julia --project -e "using Xpress"

[ Info: Xpress: Found license file /Users/USER/Applications/fico-xpress/xpressmp/bin/xpauth.xpr
ERROR: InitError: could not load library "libxprs.dylib"
dlopen(libxprs.dylib, 1): image not found
Stacktrace:
 [1] XPRSlicense(::Array{Int32,1}, ::String) at /Users/USER/gitrepos/Xpress.jl/src/lib.jl:54
 [2] license(::Array{Int32,1}, ::String) at /Users/USER/gitrepos/Xpress.jl/src/api.jl:142
 [3] userlic(; verbose::Bool, liccheck::typeof(Xpress.emptyliccheck), xpauth_path::String) at /Users/USER/gitrepos/Xpress.jl/src/license.jl:71
 [4] userlic at /Users/USER/gitrepos/Xpress.jl/src/license.jl:57 [inlined]
 [5] initialize at /Users/USER/gitrepos/Xpress.jl/src/Xpress.jl:47 [inlined]
 [6] __init__() at /Users/USER/gitrepos/Xpress.jl/src/Xpress.jl:61
 [7] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
 [8] _require_from_serialized(::String) at ./loading.jl:749
 [9] _require(::Base.PkgId) at ./loading.jl:1040
 [10] require(::Base.PkgId) at ./loading.jl:928
 [11] require(::Module, ::Symbol) at ./loading.jl:923
during initialization of module Xpress
```

If I change this to use the explicit path, it works as expected.

Resolves #109

### CODE REVIEW

File: src/Xpress.jl [hunk 1]
```diff
@@ -3,18 +3,20 @@ __precompile__()
...
     if isfile(depsjl_path)
         include(depsjl_path)
     elseif !haskey(ENV, "XPRESS_JL_NO_DEPS_ERROR")
         error("XPRESS cannot be loaded. Please run Pkg.build(\"Xpress\").")
     else
-        const dlpath = ""
+        const xpressdlpath = ""
     end
 
+    const libxprs = joinpath(xpressdlpath, string(Sys.iswindows() ? "" : "lib", "xprs", ".", Libdl.dlext))
```
Comment (joaquimg) [inline src/Xpress.jl:18]: do we need xpressdlpath here?

File: src/Xpress.jl [hunk 2]
```diff
@@ -43,7 +45,7 @@ module Xpress
     )
 
     function initialize()
-        Libdl.dlopen(joinpath(dlpath, libxprs))
+        lib = Libdl.dlopen(libxprs)
```
Comment (joaquimg) [inline src/Xpress.jl:48]: we don't need `lib = ` right?

**Review by joaquimg — CHANGES_REQUESTED** [review]
Looks good!

Btw, since you are on MAC, can you try the disable printing thing?
I thing it is still printing something it shouldn't

File: src/Xpress.jl (hunk 2 above)
Comment (kdheepak) [reply src/Xpress.jl]: Resolved in https://github.com/jump-dev/Xpress.jl/pull/110/commits/c0db24ed62b9897cea8bbf742da2c17b1a581a34.

File: src/Xpress.jl (hunk 1 above)
Comment (kdheepak) [reply src/Xpress.jl:18]: I think it need it. It will be set to an empty string if `XPRESS_JL_NO_DEPS_ERROR` is set though, for when users want to load a library that is in their environment without using deps.jl.

**Comment by kdheepak** [comment]
I rebased your branch on top of this PR (so that I could get it to work on my mac): 

Screen Shot 2020-11-19 at 6 12 09 PM

I'm still getting the message being printed.

**Review by joaquimg — APPROVED** [review]
