### ISSUE TITLE
MethodError: no method matching `joinpath(::typeof(Libdl.dlpath), ::String))`

### ISSUE THREAD

**Issue by kdheepak** [jump-dev/Xpress.jl#109]
Xpress.jl doesn't work on MacOS with version `v0.12.1`. `v0.11.1` works fine though.

```plaintext
$ git checkout v0.11.1
Previous HEAD position was 1e563eb Update Project.toml
HEAD is now at bf17091 Update Project.toml (#97)

$ julia --project -e "using Xpress;"
[ Info: Xpress: Development license detected.

$ git log -n1
commit bf170918bdb949103c5b6161349006b77e2a52e6 (HEAD, tag: v0.11.1)
Date:   Mon Sep 21 09:03:40 2020 +1200

    Update Project.toml (#97)

$ git checkout -- . && git checkout v0.12.1
Previous HEAD position was bf17091 Update Project.toml (#97)
HEAD is now at 1e563eb Update Project.toml

$ julia --project -e "using Xpress;"
WARNING: redefinition of constant libxprs. This may fail, cause incorrect answers, or produce other errors.
ERROR: InitError: MethodError: no method matching joinpath(::typeof(Libdl.dlpath), ::String)
Closest candidates are:
  joinpath(::AbstractString, ::AbstractString...) at path.jl:289
Stacktrace:
 [1] initialize() at /Users/USER/gitrepos/Xpress.jl/src/Xpress.jl:46
 [2] __init__() at /Users/USER/gitrepos/Xpress.jl/src/Xpress.jl:61
 [3] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
 [4] _require_from_serialized(::String) at ./loading.jl:749
 [5] _require(::Base.PkgId) at ./loading.jl:1040
 [6] require(::Base.PkgId) at ./loading.jl:928
 [7] require(::Module, ::Symbol) at ./loading.jl:923
during initialization of module Xpress

$ git log -n1
commit 1e563eb81895817a449a866d5622e10fa70ab0fc (HEAD, tag: v0.12.1, origin/master, origin/HEAD, master)
Date:   Fri Oct 30 11:33:42 2020 -0300

    Update Project.toml

```
